{{- if and .Values.frontend.enabled .Values.frontend.local.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "project.frontend.fullname" . }}-local-port
{{- if .Values.frontend.service.annotations }}
  annotations:
{{ toYaml .Values.frontend.service.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "project.frontend.labels" . | nindent 4 }}
{{- if .Values.frontend.service.labels }}
{{ toYaml .Values.frontend.service.labels | indent 4 }}
{{- end }}
spec:
  type: ExternalName
  externalName: host.k3d.internal
  ports:
    - port: {{ .Values.frontend.local.frontendPort }}
      targetPort: {{ .Values.frontend.local.frontendPort }}
{{- end }}
