{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.frontend.service.annotations }}
  annotations:
{{ toYaml .Values.frontend.service.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "project.frontend.labels" . | nindent 4 }}

{{- if .Values.frontend.service.labels }}
{{ toYaml .Values.frontend.service.labels | indent 4 }}
{{- end }}
  name: {{ template "project.frontend.fullname" . }}
spec:
{{- if .Values.frontend.service.nodePort }}
  type: NodePort
{{- end }}
  ports:
  - name: http
    port: {{ .Values.frontend.service.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.frontend.application.listenPort }}
  {{- if .Values.frontend.service.nodePort }}
    nodePort: {{ .Values.frontend.service.nodePort }}
  {{- end }}
  selector:
    {{- include "project.frontend.matchLabels" . | nindent 4 }}
status:
  loadBalancer: {}
{{- end }}
